// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxvgzmefwnkmtsmuxlos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dmd6bWVmd25rbXRzbXV4bG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Mzc2MDgsImV4cCI6MjA3MDExMzYwOH0.ablL8TD4-ChAF5mGtdwnKSGl3IUaVQVj174NGRx3LyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});